# fly.toml app configuration file generated for leptos-shopping-list on 2023-07-17T11:16:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leptos-shopping-list"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
